export const mentors = [
  {
    id: 1,
    name: "Rajesh Kumar",
    university: "University of ABC",
    image: require("../assets/mentor-image/mentor1.jpg"),
  },
  {
    id: 2,
    name: "Sneha Patel",
    university: "XYZ University",
    image: require("../assets/mentor-image/mentor2.jpg"),
  },
  {
    id: 3,
    name: "Amit Sharma",
    university: "University of cambridge",
    image: require("../assets/mentor-image/mentor3.jpg"),
  },
  {
    id: 4,
    name: "Priya Gupta",
    university: "Global University",
    image: require("../assets/mentor-image/mentor4.jpg"),
  },
  {
    id: 5,
    name: "Vikram Singh",
    university: "City College",
    image: require("../assets/mentor-image/mentor5.jpg"),
  },
  {
    id: 6,
    name: "Anjali Desai",
    university: "Tech Institute",
    image: require("../assets/mentor-image/mentor6.jpg"),
  },
  {
    id: 7,
    name: "Manoj Joshi",
    university: "Ocean University",
    image: require("../assets/mentor-image/mentor7.jpg"),
  },
  {
    id: 8,
    name: "Neha Patel",
    university: "Mountain State University",
    image: require("../assets/mentor-image/mentor8.jpg"),
  },
  {
    id: 9,
    name: "Sanjay Choudhury",
    university: "Greenland University",
    image: require("../assets/mentor-image/mentor9.jpg"),
  },
  {
    id: 10,
    name: "Pooja Reddy",
    university: "Sunrise College",
    image: require("../assets/mentor-image/mentor10.jpg"),
  },
  {
    id: 11,
    name: "Vishal Agrawal",
    university: "Mars University",
    image: require("../assets/mentor-image/mentor11.jpg"),
  },
  {
    id: 12,
    name: "Mehak Khanna",
    university: "Stellar Institute",
    image: require("../assets/mentor-image/mentor12.jpg"),
  },
  {
    id: 13,
    name: "Rahul Verma",
    university: "Galaxy University",
    image: require("../assets/mentor-image/mentor13.jpg"),
  },
  {
    id: 14,
    name: "Swati Jain",
    university: "Quantum College",
    image: require("../assets/mentor-image/mentor14.jpg"),
  },
  {
    id: 15,
    name: "Rajni Yadav",
    university: "Astronomy Academy",
    image: require("../assets/mentor-image/mentor15.jpg"),
  },
  {
    id: 16,
    name: "Akash Bhat",
    university: "Celestial University",
    image: require("../assets/mentor-image/mentor16.jpg"),
  },
  {
    id: 17,
    name: "Divya Malhotra",
    university: "Starlight College",
    image: require("../assets/mentor-image/mentor17.jpg"),
  },
  {
    id: 18,
    name: "Amita Sharma",
    university: "Nebula Institute",
    image: require("../assets/mentor-image/mentor18.jpg"),
  },
];
